### ISSUE TITLE
Please remove this repository and all the others. 

### ISSUE THREAD

**Issue by LifeIsStrange** [jgamblin/Mirai-Source-Code#11]
Puting the source code of this powerfull botnet on the web is insane. "for security analyst purpose !"  LOL every hackers in the World is now able to do massive DDOS like it was yesterday on dyn DNS (and so on Twitter, reddit, github, disqus, etc). 
Do you really want a web apocalypse ? No, realise that letting access to that code is criminal. 
What should you do instead ? 
I agree security analyst and researchers need to access to the code. That's why you will give the code to a trusted authority (like an ONG) and she will distribute the code only to security researchers which will need to prove their identity and their diplomas and that they work at a security firm. They prove it in showing that stuff via video (like Skype), refuse it to all the illegitimate others. 

Thank you by avance for the security of the web. 
Sorry for my bad english.

**Comment by James-Gallagher** [comment]
Hello,

Indeed it may be a little peculiar putting the source code here on Github however every security researcher should be able to see this, to study and analyse it. As for people like me who control massive services on a large number of services, this has helped better understand the botnet and how I can protect my services from it. Hence why of course this should be available to everyone.

It is powerful. Period. Power is a quantifiable metric, and protection is not. This source code will always be online even if it isn't by this author, and if anyone felt it was a security risk, it would have immediately been placed in Github's repository of legal requests and the repository would (possibly) be taken down. Nobody is sure if it was Mirai which was behind the massive DDoS on 21st October 2016, however there are clues, which means this may not have even been Mirai.

The computer fraud and abuse act which governs malware auditing dictates that anyone can write malware and put it online, just not redistribute it directly to other machines. There will be more powerful botnets coming soon, this is the beginning of a dark future.

Thanks in advance,

James Gallagher

**Comment by Golpha** [comment]
You do not prevent hyper-scale dDoS attacks by hiding the utilized tool sources.

**Comment by maija-brazen** [comment]
Please observe that there are hundreds of highly qualified whitehats out there who do not necessarily work for a firm, have a diploma or want to be identified in any form or way. The only way for a truly secure internet is to make any and all knowledge and source code available as widely as possible as soon as possible. This levels the playing field and is the only hope we have in this age.

**Comment by thewhitetulip** [comment]
The state of network security is broken, hackers have access to more spphisticated tools than sysadmins and in that war, hackers are winning. In college I had proposed to build a new kind of threat monitoring device which I'm sure is present in the world with the three letter agencies, it would have monitored the entire network to find out anomalies i.e. unauthorized users, there is a goldmine of information which is missing in the hands of the right people. Researchers need data and source code of such powerful things in place to be able to defende their networks.

**Comment by icodeface** [comment]
too young too simple

**Comment by sndnvaps** [comment]
too young too simple

**Comment by m1guelpiedrafita** [comment]
If we can't access malware code, how will we block or prevent it?

**Comment by xmacex** [comment]
I am teaching a course on Internet governance, and Infrastructure studies, and I am glad I can pull up this software and inspect it on a general level, and then discuss it with students next Tuesday when we have lectures+lab.
