### ISSUE TITLE
SCM abuse - huge binaries included

### ISSUE THREAD

**Issue by samrocketman** [jgamblin/Mirai-Source-Code#17]
https://github.com/jgamblin/Mirai-Source-Code/tree/master/cross-compile-bin includes large binaries.

```
$ du -sh cross-compile-bin
195M	cross-compile-bin
```

It's taking me over an hour to upload a proposed change based on the latest master.  These probably should not have ever been added.  Binaries (specifically release tar.gz files) should be kept out of the source.  Instead, make use of GitHub releases.

I recommend using BFG to clean out the repository. ref: https://rtyley.github.io/bfg-repo-cleaner/

For study purposes, binaries need not be included IMO.  Build instructions are enough.

**Comment by jgamblin** [comment]
Good point.  Removed tar.gz files.

**Comment by samrocketman** [comment]
@jgamblin you did not remove the tar.gz files.  They're still in the history and it's still taking me just as long to upload.  You need to actually modify the repository history to clean out the tar.gz files.  The repository is still overly large.

Please re-open this issue until it's addressed.  I had referenced BFG cleaner as a potential solution to resolving this.

**Comment by jgamblin** [comment]
Unable to do so with BFG or other tools because they are merged form a second repo. https://jorin.me/clean-git-history/

Sorry.

**Comment by samrocketman** [comment]
Then the issue will forever be unresolved.  Because they exist in the history, a clone to download them will be forced on the user.  I see this as a barrier to entry for anyone with a slow internet connection who wants to clone or contribute.

**Comment by samrocketman** [comment]
I see you fixed the size of the repo.  Thanks for doing that.  I realize it's hard to decide to overwrite old history.  Sometimes it's necessary.
