### ISSUE TITLE
Removing old objects without references from .git/objects

### ISSUE THREAD

**Issue by NoxxDev** [jgamblin/Mirai-Source-Code#22]
## Before
`du -sh .git`
![](https://puu.sh/rUPIX/729f3f4e5f.png)

## Solution
`git remote rm origin`
`echo 74019ac2184ff131eb19393e2a8ea1882643e897 > .git/info/grafts`
`git filter-branch -- --all`
`rm .git/info/grafts`
`git update-ref -d refs/original/refs/heads/master`
`git reflog expire --expire=now --all`
`git gc --prune=now --aggressive`

## Finishi
`git remote add origin https://github.com/jgamblin/Mirai-Source-Code.git`
`git push -f origin master`

## After
`du -sh .git`
![](https://puu.sh/rUQIY/bd7d475bc5.png)

My fork after removing old objects without references and fix all errors, organize build, ...
https://github.com/NoxxDev/Mirai-Source-Code/

Please, fix this to up PR for my fork

**Comment by jgamblin** [comment]
I had to change branches and delete the old branch to shrink the size.
