### ISSUE TITLE
Change password to random

### ISSUE THREAD

**Issue by jgroom33** [jgamblin/Mirai-Source-Code#26]
After successful compromise of a device, change the password to a random string.

**Comment by superchaoran** [comment]
woops, wrong email. sry 😅

Chaoran Wang,
Master of Computer Science Student
University of Illinois at Urbana-Champaign
wang374@illinois.edu
Mobile: (217) 550-2410

**Comment by jgamblin** [comment]
This is repo is for archive and research purpose only. Please take other request and builds to personal forks.

**Comment by superchaoran** [comment]
Hi Jeff,

Sure. I will change all open services passwords.

Best,
Chaoran

Chaoran Wang,
Master of Computer Science Student
University of Illinois at Urbana-Champaign
wang374@illinois.edu
Mobile: (217) 550-2410

**Comment by samrocketman** [comment]
@superchaoran Careful, you're in legal grey area by actively hacking systems with this software to change passwords.  You may be putting yourself at serious legal risk if you're caught.

**Comment by superchaoran** [comment]
😅 Thanks for the reminder. Well, I am just interested in taking a look at
this project. Never plan to actually hack other's server or do some harm.

Chaoran Wang,
Master of Computer Science Student
University of Illinois at Urbana-Champaign
wang374@illinois.edu
Mobile: (217) 550-2410
