### ISSUE TITLE
Simplify build task

### ISSUE THREAD

**Issue by jgroom33** [jgamblin/Mirai-Source-Code#27]
Build should be a single command

**Comment by m1guelpiedrafita** [comment]
Maybe this could be done by a ./install.sh script?

**Comment by jgroom33** [comment]
I'm expecting that when the randomized password and simplified build process is complete, the global community will self host thousands of mirai locally.

**Comment by jgamblin** [comment]
This is repo is for archive and research purpose only. Please take other request and builds to personal forks.
