### ISSUE TITLE
setup  environment

### ISSUE THREAD

**Issue by jiangxilong** [jgamblin/Mirai-Source-Code#28]
.

**Comment by 1493553306** [comment]
Thank you for your share. I have a problem when I setup environment.  
 when I Compiles to `./mirai/debug` like ./build.sh debug telnet.  it shows 
cnc/database.go:8:5: cannot find package **"github.com/go-sql-driver/mysql"** in any of:
	/usr/lib/go/src/pkg/github.com/go-sql-driver/mysql (from $GOROOT)
	/home/xu/Documents/go/src/github.com/go-sql-driver/mysql (from $GOPATH)
cnc/attack.go:10:5: cannot find package "github.com/mattn/go-shellwords" in any of:
	/usr/lib/go/src/pkg/github.com/mattn/go-shellwords (from $GOROOT)
	/home/xu/Documents/go/src/github.com/mattn/go-shellwords (from $GOPATH)

then I copy the script in cnc to the folder it points out . 
it shows 
package github.com/go-sql-driver/mysql
	imports github.com/mattn/go-shellwords
	imports github.com/mattn/go-shellwords
 
how should I disturbe the script from the ./mirai/cnc?

I  appreciate it  if you can help me.

**Comment by samrocketman** [comment]
No
