### ISSUE TITLE
Norton Security Triggered

### ISSUE THREAD

**Issue by RFBrost** [jgamblin/Mirai-Source-Code#29]
Should a .zip file of this project trigger a warning by Norton Security?  Projects normally don't have any executables in them, but I don't know what Norton's Malware Signature looks for.  BTW, Norton Security said that it neutralized the threat but does not explain what it did.  It does not list any files as quarantined.

[Mirai-Source-Code-master.zip](https://github.com/jgamblin/Mirai-Source-Code/files/560289/Mirai-Source-Code-master.zip)
.

**Comment by jgamblin** [comment]
It seems to have a fairly high detection rate on VT:  https://www.virustotal.com/en/file/f10667215040e87dae62dd48a5405b3b1b0fe7dbbfbf790d5300f3cd54893333/analysis/1477822491/  

Hopefully there is no reason to download the code local to do analysis on it.

**Comment by RFBrost** [comment]
On Oct 30, 2016, at 03:17 AM, Jerry Gamblin <notifications@github.com> wrote:

> Hopefully there is no reason to download the code local to do analysis on it.
> 
On further analysis it appears the project has a set of binaries in its ~/dir/release directory. 

My first reaction to this was that the binaries are un-necessary because they can be built locally, but then I realized that a researcher may not have all the platforms of interest available to them to build them all locally so the presence of the binaries serves a valid research purpose.

Perhaps a warning about the presence of the binaries in the top level docs would be advisable.

Thanks for your response.

--------------------------------------------------------------------------------------------------
Robert F. Brost                					eMail:	GitHub@Brost.net
--------------------------------------------------------------------------------------------------

**Comment by jgamblin** [comment]
I have added a warning to readme.
