### ISSUE TITLE
The database script not found

### ISSUE THREAD

**Issue by pandadao** [jgamblin/Mirai-Source-Code#33]
Hello,
     I am following the tutorial to rebuild the exam, but I click this link http://pastebin.com/86d0iL9g
It was removed, do you have the backup file?  Thank you.

**Comment by samrocketman** [comment]
ref: https://github.com/jgamblin/Mirai-Source-Code/blob/master/ForumPost.md

It is archived in https://github.com/jgamblin/Mirai-Source-Code/blob/master/scripts/db.sql

**Comment by fchiao** [comment]
btw, should add another the line
USE mirai;
after
CREATE DATABASE mirai;

**Comment by samrocketman** [comment]
@fchiao this repository isn't really for bugfixing the malware.  Only for preserving the original source release for study purposes.
