### ISSUE TITLE
Help....

### ISSUE THREAD

**Issue by kalivim** [jgamblin/Mirai-Source-Code#36]
When i run `./loader.dbg` is print:

    (1/9) bins/dlr.arm is loading...
    (2/9) bins/dlr.arm7 is loading...
    (3/9) bins/dlr.m68k is loading...
    (4/9) bins/dlr.mips is loading...
    (5/9) bins/dlr.mpsl is loading...
    (6/9) bins/dlr.ppc is loading...
    (7/9) bins/dlr.sh4 is loading...
    (8/9) bins/dlr.spc is loading...
    (9/9) bins/dlr.x86 is loading...
    Killed
I allready changed my `/dlr/main.c` file to myself http_server ip and run `build`,then `mv` to `./loader/bins/`

**Comment by samrocketman** [comment]
This is not a support forum for how to use Mirai.
