### ISSUE TITLE
People have stolen your repo and removed the LICENSE

### ISSUE THREAD

**Issue by nanalan** [jgamblin/Mirai-Source-Code#37]
https://github.com/0x27/linux.mirai
https://github.com/gblmarquez/linux.mirai
https://github.com/James-Gallagher/Mirai/

Assuming this is the original, of course :smile:

**Comment by samrocketman** [comment]
It's not really stolen.  The original sources came from a hacker forum.  It's quite possible they obtained separate copies (which as far as I know didn't come with a license at all).

This code was licensed under GPLv3 by @jgamblin when he downloaded it from the hacker forums and posted it on GitHub.  @jgamblin is not the original author of this source code as far as I know.

**Comment by jgamblin** [comment]
As @samrocketman says the GPLv3 license was added by me as the original code was  abandoned (see forum post) and reposted by me with the license after talking to a few people who needed it to be able to do academic research on it.

**Comment by hasufell** [comment]
> This code was licensed under GPLv3 by @jgamblin when he downloaded it from the hacker forums and posted it on GitHub.

How is that not stolen?

**Comment by nanalan** [comment]
> As @samrocketman says the GPLv3 license was added by me as the original code was abandoned (see forum post) and reposted by me with the license after talking to a few people who needed it to be able to do academic research on it.

So it's technically OK to repost _without_ the license? Or are you now the legitimate owner of the source?

**Comment by Freccia** [comment]
I suggest you to read 
https://krebsonsecurity.com/2016/10/source-code-for-iot-botnet-mirai-released/

**Comment by jgamblin** [comment]
(I accidently edited a previous comment and was unable to undo it). 

I dont own this code.  It was abandoned/open sourced by the original author.  I posted a copy here for research and added the GPL license because that was the best understanding of the intent of the forum post.   I have no claim to ownership of this code at all.
