### ISSUE TITLE
Bug: Fails to destroy the Internet

### ISSUE THREAD

**Issue by xmacex** [jgamblin/Mirai-Source-Code#8]
It appears that the design is incomplete or implementation buggy; except for limited inconveniences, the software fails to destroy the Internet :/

**Comment by realyze** [comment]
Maybe you're holding it wrong?

**Comment by stephenscaff** [comment]
Cute.

**Comment by EddieOne** [comment]
Github was down too. Maybe not sh*t where we eat

**Comment by samrocketman** [comment]
@EddieOne 

![don't know if serious... or just joking...](http://s2.quickmeme.com/img/00/00536d9268ae66b090ccd30f3fa270b83851de218147a6e0e4b0a7ab86af7232.jpg)
